// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmofvoekrrskgurydtnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtb2Z2b2VrcnJza2d1cnlkdG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MDk0NTMsImV4cCI6MjA4ODQ4NTQ1M30.a8SB38ryN9X06nhIFgSSDCLGYpB-vzD7eyZ8Z9PBV4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});